name: app_dev_project
description: "A comprehensive Campus Event Companion app featuring role-based access (Admin/Student), local database persistence with Hive, and a modern UI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.5+1

  # Database (Local Storage)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

  # Linter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true