name: app_dev_project
description: "A comprehensive Campus Event Companion app featuring role-based access (Admin/Student), local database persistence with Hive, and a modern UI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  uuid: ^4.5.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  table_calendar: ^3.1.2